language: php
php:
  - 7.4
before_script:
  - composer install --no-interaction
script:
  - phpunit tests
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  target-branch: gh-pages
  on:
    branch: master